server:
  port: 80
eureka:
  client:
    fetch-registry: true  #要不要去注册中心获取其他服务的地址，这里是消费端，肯定为true  并且默认为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
feign:
  hystrix:
    enabled: true
